version: '3'
services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sprobe-demo
    container_name: sprobe-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - sprobe-network

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: sprobe-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - sprobe-network

  # MySQL Service
  db:
    image: mysql:8.0
    container_name: sprobe-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - sprobe-network

networks:
  sprobe-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
